"""Rename prompt table to prompts

Revision ID: 17da819afbe3
Revises: 3aafbdebec90
Create Date: 2025-05-15 18:06:13.759510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17da819afbe3'
down_revision: Union[str, None] = '3aafbdebec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('user_prompt', sa.String(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.drop_index('ix_prompt_id', table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='prompt_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prompt_pkey')
    )
    op.create_index('ix_prompt_id', 'prompt', ['id'], unique=False)
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
